### ISSUE TITLE
Player 2 HandleAir error

### ISSUE THREAD

**Issue by slambo311** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#32]
![Screenshot_20220914-213935.png](https://user-images.githubusercontent.com/61334045/190293188-c972788e-a113-4372-936e-127cb76c3064.png)
If I turn on txtscripts in the settings, or try to use the mod version of Sonic Forever or Sonic 2 Absolute, I get this error. Just in case you need to know, I'm using the android version of the decomp.

**Comment by LittlePlanetCD** [comment]
How old or recent is this decomp installation on your device?

**Comment by slambo311** [comment]
Just installed it a few weeks ago.

**Comment by slambo311** [comment]
Not sure, but I will update it to the latest release

**Comment by slambo311** [comment]
Ok, apparently all I had to do was update to fix it.
