### ISSUE TITLE
Aquatic Ruins randomly makes p1 float in the water

### ISSUE THREAD

**Issue by Leonx254** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#34]
![RSDKv4_64_37nhqO4cSJ](https://user-images.githubusercontent.com/59059689/198202379-f2f13281-c909-4db9-af25-453e67f6d194.gif)

The place where i managed to trigger it the most is on the first pit that allows you to enter the water, in the area with the pillar, the set of three rotating platforms and an airbubbler, bubbles seems to trigger this bug the most, with the rotating platforms doing it less frequently, switching Debug Mode while moving can also force it sometimes.

This doesn't seem to affect p2

-Tested on standalone

**Comment by MegAmi24** [comment]
> bubbles seems to trigger this bug the most, with the rotating platforms doing it less frequently
can you explain what exactly this means? are they related with replicating the bug somehow?

**Comment by Leonx254** [comment]
Can't tell if the bubbles are related, but breathing them usually triggers the bug for me, in general it seems like interacting with stage objects is what triggers the bug

**Comment by Leonx254** [comment]
Fixed in https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation/commit/7894f6b4c3c93edc0a653144cc43076ad9a8ff95
