### ISSUE TITLE
v5U Legacy Cleanup: changing an option in playerobjects.txt does nothing

### ISSUE THREAD

**Issue by MarioMastr** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#35]
changing the "player.left = false" & "player.right = false" options for the function Player_State_RollJump into true does nothing. its only when i delete them that roll jump lock disables. 
<img width="794" alt="Screenshot 2022-12-21 at 17 12 45" src="https://user-images.githubusercontent.com/84964352/208964519-097c0dd8-d093-440f-8d73-c29ca3e50f33.png">

**Comment by MegAmi24** [comment]
This is an issue with your modification, not the scripts themselves, and as such is not a valid issue to post here.

**Comment by MegAmi24** [comment]
The fact you've changed it in the first place and then reported the issue here is the problem. Issues here are supposed to be about the scripts as they are on the repo with no changes.
