### ISSUE TITLE
v5U Legacy Cleanup: player.dropdashCount is not being detected

### ISSUE THREAD

**Issue by MarioMastr** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#36]
if i try to set the game version to Origins, the v5U app does not recognise the player.dropdashCountX operands and refuses to load a level
<img width="1440" alt="Screenshot 2022-12-21 at 18 32 15" src="https://user-images.githubusercontent.com/84964352/208978229-00f6edf0-b36f-4f5d-9de2-ded010a5565b.png">

**Comment by MegAmi24** [comment]
This variable doesn't exist Origins 1.00 RSDKs, make sure you're using one from 1.04
