### ISSUE TITLE
Cleanup: Oil Ocean oil streams leave Sonic trapped in place and the zone is unbeatable

### ISSUE THREAD

**Issue by MarioMastr** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#37]
<img width="1440" alt="Screenshot 2022-12-24 at 12 13 13" src="https://user-images.githubusercontent.com/84964352/209435884-0c860971-ef48-4455-abed-10801318e2c8.png">

**Comment by Leonx254** [comment]
fixed in https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation/commit/0ca7fab1a81eb2626d9a5ba9fea90d647853eb10

**Comment by MarioMastr** [comment]
Ok great thanks
