### ISSUE TITLE
MPZ EggmanBalloon bug.

### ISSUE THREAD

**Issue by Twanvanb1** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#38]
Latest clean up scripts:
![image](https://user-images.githubusercontent.com/78142253/219659297-24e34729-8a31-4afe-b937-878c7839c40d.png)

Data.rsdk:
![image](https://user-images.githubusercontent.com/78142253/219659596-17cf4059-caf3-45d6-913f-9e29dd952605.png)

**Comment by MegAmi24** [comment]
Fixed in [0d03508](https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation/commit/0d03508f217a137f9341fa3dbde881daa2cfda91)
