### ISSUE TITLE
You start with 1 Life in the dev menu/Normal save

### ISSUE THREAD

**Issue by sntxxbitch** [Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation#43]
Whenever I enter a level with the devmenu. Or in a normal or ordinary game, instead of having 3 lives I start with only one life. I even already have the scripts, it happens to me with both games (S1/S2)

**Comment by MegAmi24** [comment]
A semi-recent change in the mobile versions of the games changed the default life count to 1 instead of 3. Since this is an issue with the datafile instead of the scripts, we can't do much about it.
